name: Jalankan Prediksi AI
on:
  workflow_dispatch:
  schedule:
    # UPDATE SETIAP 5 MENIT — 24 Jam Penuh WIB
    # GitHub pakai UTC → WIB = UTC+7
    - cron: '*/5 * * * *'

jobs:
  jalankan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    env:
      TZ: Asia/Jakarta

    steps:
      - name: Ambil File
        uses: actions/checkout@v4

      - name: Siapkan Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Pasang Library
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy==1.26.4 \
                      tensorflow-cpu==2.15.0 \
                      optuna==3.6.1

      - name: Jalankan AI
        run: python jalankan_ai.py

      - name: Simpan Hasil
        run: |
          git config --global user.name "peler3773-png"
          git config --global user.email "peler3773@users.noreply.github.com"
          git add hasil_prediksi.json
          git commit -m "🤖 Update $(date +'%Y-%m-%d %H:%M WIB')" --allow-empty
          git push
